global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: spring-gateway
    metrics_path: /actuator/metrics
    static_configs:
      - targets:
          - '192.168.0.2:8118'
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'idonotexists:564'
